Repository betagouv/e-controle, pull requests merged in 2020-04, with the labels that each got.

#492 Collapse sidebar
  control/views.py
  static/src/controls/ControlPage.vue
  static/src/questionnaires/QuestionnaireCreate.vue
  static/src/questionnaires/QuestionnaireDetailPage.vue
  static/src/utils/Breadcrumbs.vue
  static/src/utils/Sidebar.vue
  templates/base.html
  templates/ecc/questionnaire_detail.html
  templates/ecc/trash.html
Labels: commando

#490 Better first experience : add button
  static/src/controls/ControlCreate.vue
  static/src/controls/NoControls.vue
Labels: commando

#494 Remove use of v-html
  static/src/questions/ResponseFileList.vue
  static/src/utils/backend.js
Labels: ey and friends

#495 Add rel attribute on links opening in new tabs
  static/src/controls/WebdavTip.vue
  static/src/questionnaires/PublishFlow.vue
  static/src/questionnaires/QuestionnaireMetadata.vue
  static/src/questions/ResponseFileList.vue
  static/src/utils/Sidebar.vue
  templates/ecc/trash.html
  tos/templates/tos/tos.html
Labels: ey and friends

#496 More secure cookies
  ecc/settings.py
Labels: ey and friends

#484 Change questionnaire docx styling
  templates/ecc/questionnaire.docx
Labels: commando

#499 Refactor delete control permission
  control/api_views.py
  control/models.py
  control/permissions.py
  control/tests/test_api_question_file.py
Labels: ey and friends

#505 Split tests into separate files
  control/tests/test_api_control.py
  control/tests/test_api_question.py
  control/tests/test_api_theme.py
Labels: ey and friends

#485 Add webdav tip in questionnaire detail page
  config/api_views.py
  control/serializers.py
  static/css/custom.css
  static/src/control-detail.js
  static/src/controls/ControlCard.vue
  static/src/controls/ControlPage.vue
  static/src/controls/ControlTitle.vue
  static/src/controls/WebdavTip.vue
  static/src/questionnaires/QuestionnaireDetailPage.vue
  static/src/questionnaires/QuestionnaireMetadata.vue
  static/src/store.js
  templates/ecc/control_detail.html
Labels: commando

#508 Fix some tests
  control/tests/test_api_question_file.py
Labels: manual merge

#509 Refactor questonnaire permission
  control/api_views.py
  control/permissions.py
Labels: ey and friends

#516 Update JS packages
  package-lock.json
  package.json
  static/src/questions/ResponseFileList.vue
  static/src/session/SessionTimeout.vue
  static/src/users/AddUserModal.vue
  static/src/users/UpdateUserModal.vue
Labels: ey and friends

#507 Passing server data to Vue
  control/views.py
  static/src/control-detail.js
  static/src/controls/ControlPage.vue
  static/src/controls/WebdavTip.vue
  static/src/questionnaire-detail.js
  static/src/questionnaires/QuestionnaireDetailPage.vue
  templates/ecc/control_detail.html
  templates/ecc/questionnaire_detail.html
Labels: ey and friends

#525 Bugfix : remove vue axios completely
  static/src/controls/ControlDeleteFlow.vue
  static/src/editors/SwapEditorButton.vue
  static/src/users/RemoveUserModal.vue
Labels: ey and friends

#530 Auth bug with firefox click
  ecc/settings.py
Labels: ey and friends

#531 Add HTMLHint as html linter, to avoid unquoted attributes in Django templates
  package-lock.json
  package.json
Labels: ey and friends

#535 Control API : Remove draft questionnaires for audited
  control/api_views.py
  control/serializers.py
  control/tests/test_api_control.py
Labels: ey and friends
